name: Build

on:
  push:
    branches: [ master ]
    paths-ignore:
    - 'README.md'
    
  pull_request:
    branches: [ master ]
    paths-ignore:
    - 'README.md'
    
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [ '6.0.x', '7.0.x' ]
    
    name: Version ${{ matrix.dotnet }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
